/*
 * This source file was generated by the Gradle 'init' task
 */

package dev.haruki7049.songserver;

/** Main class which includes a entry point. */
public class App {

  /** A main function. */
  public static void main(String[] args) {
    System.out.println("Hello world!!");
  }
}
