/*
 * This source file was generated by the Gradle 'init' task
 */

package dev.haruki7049.songserver;

/** Main class which includes a entry point. */
public class Main {

  /** A main function. */
  public static void main(String[] args) {
    System.exit(0);
  }
}
