/*
 * This source file was generated by the Gradle 'init' task
 */

package dev.haruki7049.songserver;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/** Main class which includes a entry point. */
@SpringBootApplication
public class Main {

  /** A main function. */
  public static void main(String[] args) {
    SpringApplication.run(Main.class, args);
  }
}
